server:
  port: 9100

spring:
  application:
    name: common-service
  zipkin:
    base-url: http://localhost:9411/

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#logging:
#  file:
#    path: /apps/common-service/logs
#    name: common-service.log
#  level:
#    org:
#      springframework:
#        jdbc:
#          core:
#            JdbcTemplate: DEBUG
#            StatementCreatorUtils: TRACE