server:
  port: 8080
  servlet:
    contextPath: /eureka-client

spring:
  application:
    name: EurekaClient

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true